version: '3.8'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
